# Script để setup environment variables cho Supabase Local
# Chạy sau khi start Supabase local

Write-Host "🔧 Đang thiết lập environment variables cho Supabase Local..." -ForegroundColor Green

# Lấy thông tin từ supabase status
$statusOutput = supabase status --output json 2>$null

if (-not $statusOutput) {
    Write-Host "❌ Supabase chưa được khởi động!" -ForegroundColor Red
    Write-Host "💡 Chạy: .\scripts\supabase-local.ps1 start" -ForegroundColor Yellow
    exit 1
}

try {
    $status = $statusOutput | ConvertFrom-Json
    
    $apiUrl = $status.ApiURL
    $anonKey = $status.AnonKey
    
    Write-Host "`n📝 Thông tin kết nối:" -ForegroundColor Cyan
    Write-Host "   API URL: $apiUrl" -ForegroundColor White
    Write-Host "   Anon Key: $anonKey" -ForegroundColor White
    
    # Tạo file .env.local
    $envContent = @"
# Supabase Local Configuration
# Auto-generated by setup-local-env.ps1

VITE_SUPABASE_URL=$apiUrl
VITE_SUPABASE_PUBLISHABLE_KEY=$anonKey
"@
    
    $envFile = ".env.local"
    $envContent | Out-File -FilePath $envFile -Encoding utf8 -NoNewline
    
    Write-Host "`n✅ Đã tạo file $envFile" -ForegroundColor Green
    Write-Host "💡 Khởi động lại dev server để áp dụng thay đổi" -ForegroundColor Yellow
    
} catch {
    Write-Host "❌ Lỗi khi parse thông tin Supabase" -ForegroundColor Red
    Write-Host "💡 Chạy thủ công: supabase status" -ForegroundColor Yellow
    exit 1
}

