-- Cấu hình AI: model riêng cho từng provider + thư viện prompt (system + AI Coach)
ALTER TABLE "admin_ai_models" DROP CONSTRAINT IF EXISTS admin_ai_models_model_id_key;
--> statement-breakpoint
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'admin_ai_models_provider_model_key') THEN ALTER TABLE "admin_ai_models" ADD CONSTRAINT admin_ai_models_provider_model_key UNIQUE (provider, model_id); END IF; END $$;
--> statement-breakpoint
INSERT INTO "admin_ai_prompts" (name, prompt_key, category, description, system_prompt, user_prompt_template, variables) VALUES
($lio$AI Coach — system prompt$lio$, $lio$coach.system$lio$, 'system', $lio$Nhân cách & quy tắc chính của AI Coach. Sửa ở đây sẽ thay prompt mặc định (ngữ cảnh người dùng vẫn được thêm tự động).$lio$, $lio$Bạn là một AI Life Coach thông minh, thân thiện và hữu ích. Bạn giúp người dùng với việc xây dựng thói quen, đặt mục tiêu, quản lý thời gian và phát triển bản thân. Trả lời bằng tiếng Việt, ngắn gọn và thiết thực.

QUAN TRỌNG: Luôn đưa ra gợi ý CỤ THỂ và CÓ THỂ HÀNH ĐỘNG NGAY. Mỗi gợi ý nên bao gồm:
- Hành động cụ thể
- Thời gian thực hiện (nếu có)
- Lợi ích của hành động đó$lio$, NULL, '{}'::text[]),
($lio$Trợ lý ra lệnh — hướng dẫn thêm$lio$, $lio$assistant.system$lio$, 'system', $lio$Hướng dẫn bổ sung cho trợ lý giọng nói/chat khi tạo task, thói quen, nhật ký… (để trống = mặc định).$lio$, $lio$$lio$, NULL, '{}'::text[]),
($lio$Ghi chú giọng nói — hướng dẫn thêm$lio$, $lio$voice_note.system$lio$, 'system', $lio$Hướng dẫn bổ sung khi AI biên tập lời nói thành ghi chú.$lio$, $lio$$lio$, NULL, '{}'::text[]),
($lio$Chép lời — hướng dẫn thêm$lio$, $lio$transcribe.system$lio$, 'system', $lio$Hướng dẫn bổ sung khi chép lời ghi âm.$lio$, $lio$$lio$, NULL, '{}'::text[]),
($lio$Tạo mẫu — hướng dẫn thêm$lio$, $lio$templates.system$lio$, 'system', $lio$Hướng dẫn bổ sung khi AI tạo mẫu mục tiêu/thói quen/nhật ký.$lio$, $lio$$lio$, NULL, '{}'::text[]),
($lio$Gợi ý cải thiện — hướng dẫn thêm$lio$, $lio$suggest.system$lio$, 'system', $lio$Hướng dẫn bổ sung khi gợi ý thói quen/việc cho lĩnh vực điểm thấp.$lio$, $lio$$lio$, NULL, '{}'::text[]),
($lio$Dịch thuật — hướng dẫn thêm$lio$, $lio$translate.system$lio$, 'system', $lio$Hướng dẫn bổ sung khi dịch.$lio$, $lio$$lio$, NULL, '{}'::text[]),
($lio$Tầm nhìn & giá trị — hướng dẫn thêm$lio$, $lio$vision.system$lio$, 'system', $lio$Hướng dẫn bổ sung khi gợi ý tầm nhìn, giá trị.$lio$, $lio$$lio$, NULL, '{}'::text[]),
($lio$Gợi ý giao diện — hướng dẫn thêm$lio$, $lio$theme.system$lio$, 'system', $lio$Hướng dẫn bổ sung khi AI tạo theme.$lio$, $lio$$lio$, NULL, '{}'::text[]),
($lio$Lên kế hoạch ngày$lio$, $lio$coach.plan.daily$lio$, $lio$coach:planning$lio$, $lio$Sắp xếp việc trong ngày theo ưu tiên và năng lượng$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Giúp mình lên kế hoạch cho hôm nay. Những việc cần làm: {{viec_can_lam}}. Mình có khoảng {{so_gio}} giờ làm việc. Hãy xếp theo khung giờ, đánh dấu 3 việc quan trọng nhất (MIT) và chừa thời gian nghỉ.$lio$, ARRAY['viec_can_lam','so_gio']::text[]),
($lio$Kế hoạch tuần$lio$, $lio$coach.plan.weekly$lio$, $lio$coach:planning$lio$, $lio$Chia mục tiêu tuần thành việc theo ngày$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Mình muốn lên kế hoạch tuần này. Ưu tiên tuần: {{uu_tien}}. Lịch cố định: {{lich_co_dinh}}. Hãy chia thành việc cụ thể cho từng ngày (T2–CN), kèm 1 thói quen hỗ trợ.$lio$, ARRAY['uu_tien','lich_co_dinh']::text[]),
($lio$Chia nhỏ dự án$lio$, $lio$coach.plan.breakdown$lio$, $lio$coach:planning$lio$, $lio$Biến một dự án lớn thành các bước nhỏ$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Chia dự án "{{du_an}}" (hạn: {{han}}) thành các mốc và task nhỏ ≤ 2 giờ. Đưa ra thứ tự thực hiện, việc nào làm ngay hôm nay.$lio$, ARRAY['du_an','han']::text[]),
($lio$Đặt mục tiêu SMART$lio$, $lio$coach.goal.smart$lio$, $lio$coach:goals$lio$, $lio$Biến mong muốn mơ hồ thành mục tiêu SMART$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Mình muốn: {{mong_muon}}. Hãy giúp chuyển thành mục tiêu SMART, kèm 3 kết quả then chốt (key results) và việc đầu tiên nên làm trong 24 giờ tới.$lio$, ARRAY['mong_muon']::text[]),
($lio$Rà soát tiến độ mục tiêu$lio$, $lio$coach.goal.review$lio$, $lio$coach:goals$lio$, $lio$Đánh giá mục tiêu đang chậm và điều chỉnh$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Dựa trên các mục tiêu hiện tại của mình, mục tiêu nào đang chậm? Vì sao có thể như vậy, và điều chỉnh gì cho {{khoang_thoi_gian}} tới?$lio$, ARRAY['khoang_thoi_gian']::text[]),
($lio$Tầm nhìn 1 năm$lio$, $lio$coach.goal.vision$lio$, $lio$coach:goals$lio$, $lio$Hình dung bản thân sau 1 năm và mục tiêu quý$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Giúp mình viết tầm nhìn 1 năm cho các lĩnh vực: {{linh_vuc}}. Sau đó đề xuất 1 mục tiêu cho mỗi quý.$lio$, ARRAY['linh_vuc']::text[]),
($lio$Xây thói quen mới$lio$, $lio$coach.habit.build$lio$, $lio$coach:habits$lio$, $lio$Thiết kế thói quen theo nguyên tắc Atomic Habits$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Mình muốn tạo thói quen: {{thoi_quen}}. Hãy thiết kế theo 4 quy luật (rõ ràng, hấp dẫn, dễ, thỏa mãn): phiên bản 2 phút, gắn với thói quen có sẵn, cách theo dõi.$lio$, ARRAY['thoi_quen']::text[]),
($lio$Bỏ thói quen xấu$lio$, $lio$coach.habit.break$lio$, $lio$coach:habits$lio$, $lio$Phân tích kích hoạt và thay thế thói quen xấu$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Mình muốn bỏ: {{thoi_quen_xau}}. Thường xảy ra khi: {{tinh_huong}}. Phân tích yếu tố kích hoạt, phần thưởng và đề xuất hành vi thay thế.$lio$, ARRAY['thoi_quen_xau','tinh_huong']::text[]),
($lio$Vì sao mình bỏ dở?$lio$, $lio$coach.habit.slump$lio$, $lio$coach:habits$lio$, $lio$Tìm nguyên nhân chuỗi thói quen bị đứt$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Mình hay bỏ dở thói quen {{thoi_quen}} sau khoảng {{so_ngay}} ngày. Hỏi mình 3 câu để tìm nguyên nhân rồi đề xuất cách quay lại.$lio$, ARRAY['thoi_quen','so_ngay']::text[]),
($lio$Thoát trì hoãn$lio$, $lio$coach.prod.procrastination$lio$, $lio$coach:productivity$lio$, $lio$Bắt đầu ngay việc đang né tránh$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Mình đang trì hoãn: {{viec}}. Giúp mình hiểu lý do và đưa ra bước nhỏ nhất có thể làm trong 5 phút tới.$lio$, ARRAY['viec']::text[]),
($lio$Ma trận Eisenhower$lio$, $lio$coach.prod.eisenhower$lio$, $lio$coach:productivity$lio$, $lio$Phân loại việc khẩn cấp / quan trọng$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Phân loại các việc sau vào ma trận Eisenhower và gợi ý việc nào nên làm, lên lịch, ủy thác hay bỏ: {{danh_sach_viec}}$lio$, ARRAY['danh_sach_viec']::text[]),
($lio$Tập trung sâu$lio$, $lio$coach.prod.deepwork$lio$, $lio$coach:productivity$lio$, $lio$Thiết lập phiên làm việc sâu$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Mình cần tập trung {{so_phut}} phút cho {{viec}}. Gợi ý cách chuẩn bị môi trường, chia Pomodoro và xử lý xao nhãng.$lio$, ARRAY['so_phut','viec']::text[]),
($lio$Nhìn lại cuối ngày$lio$, $lio$coach.reflect.daily$lio$, $lio$coach:reflection$lio$, $lio$3 câu hỏi review cuối ngày$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Hôm nay mình đã: {{hom_nay}}. Hãy giúp mình nhìn lại: điều làm tốt, điều cần cải thiện, 1 việc ưu tiên cho ngày mai.$lio$, ARRAY['hom_nay']::text[]),
($lio$Review tuần$lio$, $lio$coach.reflect.weekly$lio$, $lio$coach:reflection$lio$, $lio$Tổng kết tuần và bài học$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Giúp mình review tuần qua dựa trên dữ liệu thói quen/task/mục tiêu của mình. Điểm sáng, điểm nghẽn, bài học và 3 cam kết tuần tới.$lio$, '{}'::text[]),
($lio$Câu hỏi nhật ký$lio$, $lio$coach.reflect.journal$lio$, $lio$coach:reflection$lio$, $lio$Gợi ý câu hỏi viết nhật ký theo tâm trạng$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Tâm trạng của mình hôm nay: {{tam_trang}}. Gợi ý 5 câu hỏi viết nhật ký phù hợp để hiểu bản thân hơn.$lio$, ARRAY['tam_trang']::text[]),
($lio$Gỡ rối suy nghĩ$lio$, $lio$coach.mind.reframe$lio$, $lio$coach:mindset$lio$, $lio$Nhìn lại suy nghĩ tiêu cực (CBT)$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Mình đang nghĩ: "{{suy_nghi}}". Giúp mình nhận diện lỗi tư duy, tìm bằng chứng ủng hộ/phản bác và viết lại suy nghĩ cân bằng hơn.$lio$, ARRAY['suy_nghi']::text[]),
($lio$Động lực khi nản$lio$, $lio$coach.mind.motivation$lio$, $lio$coach:mindset$lio$, $lio$Lấy lại động lực$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Mình đang nản vì {{ly_do}}. Nhắc mình vì sao mục tiêu này quan trọng và gợi ý 1 chiến thắng nhỏ có thể đạt hôm nay.$lio$, ARRAY['ly_do']::text[]),
($lio$Kế hoạch ngủ tốt$lio$, $lio$coach.health.sleep$lio$, $lio$coach:health$lio$, $lio$Cải thiện giấc ngủ$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Mình thường ngủ lúc {{gio_ngu}} và dậy lúc {{gio_day}}, cảm thấy {{cam_giac}}. Đề xuất lịch ngủ và thói quen trước khi ngủ.$lio$, ARRAY['gio_ngu','gio_day','cam_giac']::text[]),
($lio$Lịch vận động$lio$, $lio$coach.health.workout$lio$, $lio$coach:health$lio$, $lio$Kế hoạch tập luyện phù hợp$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Mục tiêu sức khỏe: {{muc_tieu}}. Mình có {{thoi_gian}} mỗi ngày và trình độ {{trinh_do}}. Lên lịch tập 1 tuần đơn giản.$lio$, ARRAY['muc_tieu','thoi_gian','trinh_do']::text[]),
($lio$Ngân sách tháng$lio$, $lio$coach.fin.budget$lio$, $lio$coach:finance$lio$, $lio$Lập ngân sách theo quy tắc 50/30/20$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Thu nhập tháng của mình khoảng {{thu_nhap}}. Chi tiêu chính: {{chi_tieu}}. Lập ngân sách và gợi ý chỗ có thể tiết kiệm.$lio$, ARRAY['thu_nhap','chi_tieu']::text[]),
($lio$Mục tiêu tiết kiệm$lio$, $lio$coach.fin.saving$lio$, $lio$coach:finance$lio$, $lio$Kế hoạch tiết kiệm cho mục tiêu$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Mình muốn tiết kiệm {{so_tien}} cho {{muc_dich}} trong {{thoi_han}}. Mỗi tháng cần để dành bao nhiêu và thói quen tài chính nào hỗ trợ?$lio$, ARRAY['so_tien','muc_dich','thoi_han']::text[]),
($lio$Lộ trình học$lio$, $lio$coach.learn.roadmap$lio$, $lio$coach:learning$lio$, $lio$Lộ trình học kỹ năng mới$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Mình muốn học {{ky_nang}}, mỗi ngày {{thoi_gian}}. Tạo lộ trình 4 tuần với tài liệu, bài tập và cách tự kiểm tra.$lio$, ARRAY['ky_nang','thoi_gian']::text[]),
($lio$Ôn tập chủ động$lio$, $lio$coach.learn.recall$lio$, $lio$coach:learning$lio$, $lio$Tạo câu hỏi ôn tập$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Tạo 10 câu hỏi ôn tập (từ dễ đến khó) về chủ đề: {{chu_de}}, kèm đáp án ngắn ở cuối.$lio$, ARRAY['chu_de']::text[]),
($lio$Chuẩn bị cuộc trò chuyện khó$lio$, $lio$coach.rel.conversation$lio$, $lio$coach:relationships$lio$, $lio$Lên kịch bản trao đổi tế nhị$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Mình cần nói chuyện với {{nguoi}} về {{van_de}}. Giúp mình chuẩn bị cách mở lời, các ý chính và cách phản hồi nếu họ không đồng ý.$lio$, ARRAY['nguoi','van_de']::text[]),
($lio$Nuôi dưỡng mối quan hệ$lio$, $lio$coach.rel.nurture$lio$, $lio$coach:relationships$lio$, $lio$Hành động nhỏ để gắn kết$lio$, $lio$Bạn là AI Life Coach. Trả lời bằng tiếng Việt, cụ thể, có bước hành động.$lio$, $lio$Gợi ý 5 hành động nhỏ trong tuần để gắn kết hơn với {{nguoi}} (mối quan hệ: {{quan_he}}).$lio$, ARRAY['nguoi','quan_he']::text[])
ON CONFLICT (prompt_key) DO NOTHING;
